### ISSUE TITLE
redux-logic-test

### ISSUE THREAD

**Issue by kopax** [jeffbski/react-boilerplate-logic#2]
# react-boilerplate-logic

Would it be possible to add [redux-logic-test](https://github.com/jeffbski/redux-logic-test) unit test as a demo in this boilerplate ?

## Issue Type

- [ ] Bug (https://github.com/jeffbski/react-boilerplate-logic/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/jeffbski/react-boilerplate-logic/blob/master/.github/CONTRIBUTING.md#feature-requests)

**Comment by jeffbski** [comment]
yes, that would be a great idea.
